# Generated by Django 3.1.4 on 2021-09-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=64, verbose_name='Apellido')),
                ('matricula', models.CharField(default='YYYY', max_length=4, verbose_name='Matricula')),
                ('edad', models.IntegerField(verbose_name='Edad')),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Math')),
                ('geo', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Math')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiantes')),
            ],
        ),
    ]
