# Generated by Django 3.1.4 on 2021-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='notas',
            name='estudiante',
            field=models.ManyToManyField(to='app.Estudiantes'),
        ),
    ]
