# Generated by Django 3.1.4 on 2021-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211002_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Argentina', max_length=64, null=True, verbose_name='Nacionalidad'),
        ),
    ]
